# Generated by Django 4.2.20 on 2025-06-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telegram_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телеграм id'),
        ),
    ]
