# Generated by Django 4.2.20 on 2025-03-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telegram_id',
            field=models.TextField(blank=True, default='', verbose_name='телеграм id'),
        ),
    ]
