# Generated by Django 4.2.20 on 2025-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='телеграм id'),
        ),
    ]
