# Generated by Django 4.2.20 on 2025-04-11 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bag', '0009_alter_token_char_alter_token_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_one_tokens', models.IntegerField(default=0)),
                ('zero_tokens', models.IntegerField(default=0)),
                ('minus_one_tokens', models.IntegerField(default=0)),
                ('minus_two_tokens', models.IntegerField(default=0)),
                ('minus_tree_tokens', models.IntegerField(default=0)),
                ('minus_four_tokens', models.IntegerField(default=0)),
                ('minus_five_tokens', models.IntegerField(default=0)),
                ('minus_six_tokens', models.IntegerField(default=0)),
                ('minus_seven_tokens', models.IntegerField(default=0)),
                ('minus_eight_tokens', models.IntegerField(default=0)),
                ('star_tokens', models.IntegerField(default=0)),
                ('tentacle_tokens', models.IntegerField(default=0)),
                ('kthulhu_tokens', models.IntegerField(default=0)),
                ('hood_tokens', models.IntegerField(default=0)),
                ('skull_tokens', models.IntegerField(default=0)),
                ('tablet_tokens', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_2', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Статистика 2',
                'verbose_name_plural': 'Статистика 2',
            },
        ),
        migrations.CreateModel(
            name='Statistic_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_1', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_1', to='bag.token', verbose_name='Жетон')),
            ],
            options={
                'verbose_name': 'Статистика 1',
                'verbose_name_plural': 'Статистика 1',
                'ordering': ('owner', 'token__ordering'),
            },
        ),
    ]
