# Generated by Django 4.2.20 on 2025-04-24 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statistic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bag', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic_2',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_2', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='statistic_1',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_1', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='statistic_1',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_1', to='bag.token', verbose_name='Жетон'),
        ),
    ]
