# Generated by Django 4.2.20 on 2025-04-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'мешок',
                'verbose_name_plural': 'Мешки',
                'ordering': ('owner', 'token__ordering'),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20, verbose_name='Название')),
                ('char', models.CharField(max_length=5, verbose_name='Символ/смайл')),
                ('sticker_id', models.CharField(max_length=50, verbose_name='Стикер в телеграмме')),
                ('image', models.ImageField(blank=True, upload_to='tokens', verbose_name='Изображение')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок выдачи')),
            ],
            options={
                'verbose_name': 'жетон',
                'verbose_name_plural': 'Жетоны',
                'ordering': ('ordering',),
            },
        ),
    ]
