# Generated by Django 4.2.20 on 2025-03-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='image',
            field=models.ImageField(upload_to='tokens', verbose_name='Изображение'),
        ),
    ]
