# Generated by Django 4.2.20 on 2025-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_alter_token_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='char',
            field=models.CharField(max_length=5, verbose_name='Символ/смайл'),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='token',
            name='sticker_id',
            field=models.CharField(max_length=50, verbose_name='Стикер в телеграмме'),
        ),
    ]
