# Generated by Django 4.2.20 on 2025-03-19 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bag', '0004_alter_token_char_alter_token_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'verbose_name': 'мешок', 'verbose_name_plural': 'Мешки'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('ordering',), 'verbose_name': 'жетон', 'verbose_name_plural': 'Жетоны'},
        ),
        migrations.AddField(
            model_name='token',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок выдачи'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags', to='bag.token', verbose_name='Жетон'),
        ),
    ]
