# Generated by Django 4.2.20 on 2025-03-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0005_alter_bag_options_alter_token_options_token_ordering_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'ordering': ('token__ordering',), 'verbose_name': 'мешок', 'verbose_name_plural': 'Мешки'},
        ),
    ]
