# Generated by Django 4.2.20 on 2025-03-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0006_alter_bag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'ordering': ('owner', 'token__ordering'), 'verbose_name': 'мешок', 'verbose_name_plural': 'Мешки'},
        ),
    ]
