# Generated by Django 4.2.20 on 2025-03-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0007_alter_bag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='char',
            field=models.SlugField(max_length=5, verbose_name='Символ/смайл'),
        ),
    ]
