# Generated by Django 4.2.20 on 2025-03-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0008_alter_token_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='char',
            field=models.CharField(max_length=5, verbose_name='Символ/смайл'),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.SlugField(max_length=20, verbose_name='Название'),
        ),
    ]
