# Generated by Django 4.2.20 on 2025-04-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0009_alter_token_char_alter_token_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='image',
            field=models.ImageField(blank=True, upload_to='tokens', verbose_name='Изображение'),
        ),
    ]
